apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault
spec:
#  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/tmp